use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Params {
    pub dt: f32,
    pub history_window: usize,
    pub r_max: f32,
    pub yield_point: f32,
    pub alpha_resistance: f32,
    pub tension_threshold: f32,
    pub shear_cost_factor: f32,
    pub collapse_threshold: f32,
    pub collapse_window: usize,
    pub phi_c: f32,
    pub min_edges: usize,
    pub base_cost: f32,
    pub physical_multiplier: f32,
    pub coupling_amplification: f32,
    pub mass_delta_max: f32,
    pub zombie_decay: f32,
    pub energy_capacity: f32,
    pub energy_regen_rate: f32,
    pub bridge_activity_cost: f32,
    pub k_mass: f32,
    pub k_mass_damp: f32,
    pub stress_gain: f32,
    pub stress_midpoint: f32,
    pub stress_ema_beta: f32,
    pub w_shear: f32,
    pub w_collapse: f32,
    pub w_resources: f32,
    pub friction: f32,
    pub decay_val: f32,
    pub decay_ar: f32,
    pub decay_flow: f32,
    pub decay_tr: f32,
    pub k_kin: f32,
    pub k_val: f32,
    pub k_ar: f32,
    pub k_flow: f32,
    pub k_tr: f32,
    pub k_rep: f32,
    pub k_ep: f32,
    pub k_pe: f32,
    pub k_ec: f32,
    pub k_ce: f32,
    pub k_pc: f32,
    pub k_se: f32,
    pub k_sc: f32,
    pub k_cs: f32,
    pub trust_threshold: f32,
}

impl Default for Params {
    fn default() -> Self {
        Self {
            dt: 1.0,
            history_window: 64,
            r_max: 1.0,
            yield_point: 0.9,
            alpha_resistance: 0.8,
            tension_threshold: 0.15,
            shear_cost_factor: 0.1,
            collapse_threshold: 0.4,
            collapse_window: 64,
            phi_c: 0.5,
            min_edges: 3,
            base_cost: 0.05,
            physical_multiplier: 3.0,
            coupling_amplification: 2.0,
            mass_delta_max: 0.01,
            zombie_decay: 0.99,
            energy_capacity: 1.0,
            energy_regen_rate: 0.01,
            bridge_activity_cost: 0.02,
            k_mass: 0.001,
            k_mass_damp: 0.5,
            stress_gain: 4.0,
            stress_midpoint: 0.5,
            stress_ema_beta: 0.9,
            w_shear: 0.4,
            w_collapse: 0.4,
            w_resources: 0.2,
            friction: 0.1,
            decay_val: 0.05,
            decay_ar: 0.1,
            decay_flow: 0.1,
            decay_tr: 0.02,
            k_kin: 0.5,
            k_val: 0.5,
            k_ar: 0.3,
            k_flow: 0.5,
            k_tr: 0.2,
            k_rep: 0.3,
            k_ep: 0.4,
            k_pe: 0.2,
            k_ec: 0.3,
            k_ce: 0.3,
            k_pc: 0.2,
            k_se: 0.5,
            k_sc: 0.3,
            k_cs: 0.2,
            trust_threshold: 0.4,
        }
    }
}
